pub mod home;
pub mod schedules;
pub mod class;
pub mod generate;
mod test_generate;
mod classes;
mod teachers;
mod teacher;
mod timetable;
//mod teacher;
//pub mod common_exam;
//pub mod deneme_generate;
